0424 repo already on aws, can be checked
weichen-lin/taipei-day-trip-website pull request #2
Opened 2021-04-24 16:07 UTC by WeiChen-Lin

-> 林瑋晨
2021.04.24 _ 作業完成，已部屬到AWS上，以下為測試IP
http://52.76.36.230:3000/api/attractions?page=1
http://52.76.36.230:3000/api/attractions?page=0&keyword=藝術
http://52.76.36.230:3000/api/attraction/100

0423的commit (6d9fa48) 為clone到aws所用

2021-04-24 16:59 UTC, cwpeng requested changes
1. 請按照 API 的最小值說明，從 page=0 當作第一頁。
2. 關鍵字搜尋的結果並不正確，例如：
http://52.76.36.230:3000/api/attractions?page=1&keyword=步道
回應裡頭包含完全無關的景點資訊

2021-04-25 07:17 UTC, WeiChen-Lin commented
@cwpeng 老師你好我已修改過code，以下為測試IP

2021.04.25_modify some return format

http://52.76.36.230:3000/api/attractions?page=1
http://52.76.36.230:3000/api/attractions?page=0&keyword=藝術
http://52.76.36.230:3000/api/attraction/100

2021-04-25 07:30 UTC, cwpeng requested changes
以下兩個網址請確認：
http://52.76.36.230:3000/api/attractions?page=0
http://52.76.36.230:3000/api/attractions?page=0&keyword=臺北

要整體性的去看結果哦 ~

2021-04-25 08:08 UTC, WeiChen-Lin commented
2021_0425_16:05再次修改 
再請老師確認了! 感謝老師，測試IP為

http://52.76.36.230:3000/api/attractions?page=0
http://52.76.36.230:3000/api/attractions?page=0&keyword=臺北
http://52.76.36.230:3000/api/attraction/100

by 林瑋晨

2021-04-25 12:36 UTC, cwpeng approved these changes
OK. 有滿足基本要求。

不過額外建議，不要一次把所有資料撈出來，在程式中篩選頁數，一次撈全部的資料這件事情一直都是大忌，未來請多注意，直接使用 SQL 的 LIMIT 語句處理會更實際。

2021-04-25 13:35 UTC, WeiChen-Lin commented
@cwpeng  謝謝老師的建議，我沒有想到這裡。老師我可以先想想如何達成，等讓老師看過之後OK之後再merge上去嗎?

2021-04-25 13:37 UTC, cwpeng commented
可哦

2021-04-26 03:18 UTC, WeiChen-Lin commented
0426 11:15 已更改拿出data方式，再請老師幫我看看，感謝老師!

2021-04-26 07:30 UTC, cwpeng commented
沒問題哦，很好的改善 ~

2021-04-26 09:39 UTC, merged