林瑋晨_Week3 作業
weichen-lin/taipei-day-trip-website pull request #4
Opened 2021-05-06 06:39 UTC by WeiChen-Lin

<林瑋晨>

老師您好，這是week3的作業，測試網址為
http://52.76.36.230:3000/
感謝老師，目前功能測試正常，我自己認為我的css要大改，不過最近因為工作關係，我會慢慢開始改css，可能會花1-2個禮拜。
麻煩老師了，感謝!

2021-05-06 14:42 UTC, cwpeng requested changes
以下截圖是 400px 的螢幕，也是常見的手機尺寸，版面跑掉很多，包括主視覺的圖片會變形等等，就等你改完之後再給我看嘍 ~

![52 76 36 230_3000_attraction_2](https://user-images.githubusercontent.com/6104683/117317706-564e7880-aebc-11eb-90be-72b7a1bff6a5.png)

2021-05-07 16:47 UTC, WeiChen-Lin commented
<林瑋晨>
老師您好，已修改好，測試網址為
http://52.76.36.230:3000/
css在attraction頁面有大改，所以和首頁可能會有點不同，謝謝老師!

2021-05-07 17:09 UTC, cwpeng requested changes
手機版面是 OK，不過中大型的螢幕版面都出了狀況：
1. 只要螢幕尺寸大於 1200px，我們的中央內容區塊都應該固定在 1200px 的空間中左右貼齊。
2. 你的輪播圖片的比例沒辦法在各種常見螢幕解析度中保持不動，圖片比例會跑掉 ( 拉長或變扁 )

請參考以下第一張圖，是 1300px 寬的螢幕，中小型的筆電都是這個尺寸，你的中央內容區縮到只剩下 800px 寬左右，導致圖片也被壓扁。
![52 76 36 230_3000_attraction_2](https://user-images.githubusercontent.com/6104683/117484556-cda60a00-af99-11eb-81b3-4d141660d9aa.png)

請參考以下第二張圖，是 768px 寬的螢幕，在 iPad 上就是這種樣子，雖然沒那麼重要，可以比較隨興，但嚴重的版面混亂還是很難接受。
![52 76 36 230_3000_attraction_2 (1)](https://user-images.githubusercontent.com/6104683/117484651-f62e0400-af99-11eb-99d0-d8511e58c260.png)

2021-05-08 16:06 UTC, WeiChen-Lin commented
<林瑋晨>
老師您好，已修改好，測試網址為
http://52.76.36.230:3000/

辛苦老師了! 感謝老師~

2021-05-08 16:32 UTC, cwpeng approved these changes
好哦，有改善不少，這樣就可以了 ~

2021-05-10 03:22 UTC, merged